lr: 5e-6
target_length: 1
dem: True
climate: timeseries
task: segmentation
feature_dim: 512
hidden_channels: 64
kernel_size: 3
padding: 1
stride: 1
bias: True
batch_first: True
bidirectional: False
in_channels: 6 # 7
skip_connections: True
backbone: convnextv2_large
act_layer: identity
seq_len: ${dataset.seq_len}
